/// Builds the public website (roadmap W1, `docs/HANDOVER.md`).
///
/// Three outputs, none committed — the deploy builds the site, nobody
/// commits it:
///
/// - `web/sample.js`, the 90.05 job deck's mirror text as one JavaScript
///   string, so the page carries its sample program with no request.
/// - `web/main.wasm` and `web/main.mjs`, the compiler itself.
///
/// **The target is WebAssembly, not JavaScript, and the choice is
/// load-bearing.** A Dart `int` compiled to JavaScript is a double, and its
/// bitwise operators truncate to 32 bits. A 7090 word is 36 bits, so the
/// JavaScript build silently drops the top four bits of every packed word:
/// the semantics and code dumps print `006060606060` where the machine held
/// `606060606060`. WebAssembly gives a true 64-bit `int` and reproduces all
/// six goldens byte for byte. Measured 2026-08-10; the same trap waits for
/// the M4 emulator in a browser.
///
/// Run it from the repository root:
///
///     dart run tool/build_web.dart
library;

import 'dart:convert';
import 'dart:io';

const String _sampleDeck = 'test/fixtures/90.05-payroll-job.ct';

void main() {
  final String sample = File(_sampleDeck).readAsStringSync();
  File('web/sample.js').writeAsStringSync(
    '// Generated by tool/build_web.dart from $_sampleDeck.\n'
    'export const SAMPLE = ${jsonEncode(sample)};\n',
  );
  stdout.writeln('web/sample.js — ${'\n'.allMatches(sample).length} cards');

  final ProcessResult compile = Process.runSync(Platform.resolvedExecutable, [
    'compile',
    'wasm',
    '-O2',
    '-o',
    'web/main.wasm',
    'web/main.dart',
  ]);
  stdout.write(compile.stdout);
  stderr.write(compile.stderr);
  if (compile.exitCode != 0) {
    exitCode = compile.exitCode;
    return;
  }
  final int bytes = File('web/main.wasm').lengthSync();
  stdout.writeln('web/main.wasm — ${(bytes / 1024).round()} KB');
}
