/// Builds the rendered mirror of the language definition — the routine
/// shared by the generator (`tool/generate_definition_mirror.dart`) and its
/// golden test (`test/definition_mirror_test.dart`).
///
/// `docs/comtran-language-definition.md` is canon and stays one file. It is
/// larger than GitHub's 512 KB limit for Markdown rendering, so a browser
/// shows it as plain text: no headings, no contents, and no anchor that
/// resolves. Every link into the definition from another document dies at
/// that limit. The mirror under `docs/definition/` holds the same text,
/// split at each level-2 heading, and every part renders.
///
/// The split is mechanical. It rewrites three things and adds one banner:
///
/// 1. An anchor link whose heading lands in another part gains that part's
///    file name. An anchor inside the same part is left alone.
/// 2. A relative path gains one `../`, because the mirror sits one
///    directory below canon.
/// 3. Each part carries the manual-link definitions whose labels it uses,
///    and no others.
///
/// The three short sections before section 1 — "Sources and authority",
/// "Where to look" and "Contents" — go into the index instead of a part of
/// their own. "Sources and authority" is the one home for the F/J rule, so
/// its anchor must stay reachable from `README.md` and `docs/HANDOVER.md`.
///
/// Canon is authoritative. Correct canon, then regenerate.
library;

import 'dart:io';

import 'manual_map_source.dart' show Slugger, plainHeading, slugify;

/// The repository-relative path of the canonical definition.
const String definitionPath = 'docs/comtran-language-definition.md';

/// The repository-relative directory the mirror is written to.
const String mirrorDirectory = 'docs/definition';

/// The file name of the mirror's index.
const String mirrorIndex = 'README.md';

/// The first line of every generated file.
const String mirrorBanner =
    '<!-- Generated by tool/generate_definition_mirror.dart. Do not edit. -->';

/// The level-2 headings the index holds, instead of a part file each.
const List<String> indexSections = <String>[
  'Sources and authority',
  'Where to look',
  'Contents',
];

final RegExp _fence = RegExp('^ {0,3}```');
final RegExp _heading = RegExp(r'^(#{1,6}) +(.*)$');
final RegExp _anchorLink = RegExp(r'\]\(#([^)]+)\)');
final RegExp _upLink = RegExp(r'\]\(\.\./');
final RegExp _linkDefinition = RegExp(r'^\[([^\]]+)\]: +(.*)$');
final RegExp _leadingNumber = RegExp(r'^\d+\.\s+');

/// One level-2 section of the definition: its heading `title`, the output
/// `file` that holds it, and its `lines` including the heading itself.
typedef MirrorPart = ({String title, String file, List<String> lines});

/// The anchor of the heading whose markdown text is [text]: the display
/// form first, then GitHub's slug of it.
String slugifyHeading(String text) => slugify(plainHeading(text));

/// The mirror as repository-relative paths mapped to file contents, sorted
/// by path.
Map<String, String> buildDefinitionMirror({String? markdown}) {
  final String source = markdown ?? File(definitionPath).readAsStringSync();
  final List<String> lines = source.split('\n');

  final int blockStart = _linkBlockStart(lines);
  final List<String> body = lines.sublist(0, blockStart);
  final Map<String, String> definitions = _linkDefinitions(
    lines.sublist(blockStart),
  );

  final List<MirrorPart> parts = _split(body);
  final Map<String, String> ownerOf = _anchorOwners(body, parts);

  final output = <String, String>{};
  final int total = parts.length - 1;
  for (var p = 0; p < parts.length; p++) {
    final MirrorPart part = parts[p];
    output['$mirrorDirectory/${part.file}'] = _render(
      part.lines,
      ownerOf,
      part.file,
      definitions,
      nav: p == 0
          ? null
          : 'Part $p of $total of the '
                '[COMTRAN Language Definition]($mirrorIndex).',
    );
  }
  return Map<String, String>.fromEntries(
    output.entries.toList()..sort((a, b) => a.key.compareTo(b.key)),
  );
}

/// The index of the first line of the trailing manual-link block, or the
/// line count when the file has no block.
int _linkBlockStart(List<String> lines) {
  for (int i = lines.length - 1; i >= 0; i--) {
    if (lines[i].startsWith('<!-- manual links;')) {
      return i;
    }
  }
  return lines.length;
}

/// The label-to-target map of the trailing manual-link block, with each
/// relative target moved one directory down.
Map<String, String> _linkDefinitions(List<String> block) {
  final result = <String, String>{};
  for (final line in block) {
    final RegExpMatch? match = _linkDefinition.firstMatch(line);
    if (match != null) {
      result[match[1]!] = _descend(match[2]!);
    }
  }
  return result;
}

/// [path] as seen from one directory below where it was written.
String _descend(String path) => path.startsWith('../') ? '../$path' : path;

/// Splits [body] at each level-2 heading. The lines before the first one,
/// and the [indexSections], go to the index; the rest take a numbered file
/// each.
List<MirrorPart> _split(List<String> body) {
  final starts = <int>[];
  var fenced = false;
  for (var i = 0; i < body.length; i++) {
    if (_fence.hasMatch(body[i])) {
      fenced = !fenced;
    } else if (!fenced && body[i].startsWith('## ')) {
      starts.add(i);
    }
  }

  final index = <String>[...body.sublist(0, starts.first)];
  final parts = <MirrorPart>[];
  for (var s = 0; s < starts.length; s++) {
    final int end = s + 1 < starts.length ? starts[s + 1] : body.length;
    final List<String> section = body.sublist(starts[s], end);
    final String title = plainHeading(body[starts[s]].substring(3));
    if (indexSections.contains(title)) {
      index.addAll(section);
      continue;
    }
    parts.add((
      title: title,
      file: _fileName(parts.length + 1, title),
      lines: section,
    ));
  }

  return <MirrorPart>[
    (title: 'index', file: mirrorIndex, lines: _withNote(index)),
    ...parts,
  ];
}

/// The file name of part [number] titled [title]: the ordinal, then the
/// title's anchor with its own leading ordinal removed.
String _fileName(int number, String title) {
  final String slug = slugify(title.replaceFirst(_leadingNumber, ''));
  return '${number.toString().padLeft(2, '0')}-$slug.md';
}

/// [index] with the note that explains why the mirror exists, placed after
/// the definition's own opening paragraph.
List<String> _withNote(List<String> index) {
  final int firstHeading = index.indexWhere(
    (String line) => line.startsWith('## '),
  );
  return <String>[
    ...index.sublist(0, firstHeading),
    '> **This is a reading copy.** `../comtran-language-definition.md` is',
    '> canon. That file is larger than the 512 KB limit for Markdown',
    '> rendering on GitHub, so a browser cannot show it as a document. This',
    '> directory holds the same text in parts, and each part renders. A',
    '> generator writes these files. Do not edit them: correct canon, then',
    '> run `dart run tool/generate_definition_mirror.dart`.',
    '',
    ...index.sublist(firstHeading),
  ];
}

/// Every heading anchor in [body] mapped to the file that holds it. One
/// slugger runs over the whole document, because canon is one file and its
/// anchors are unique across it.
Map<String, String> _anchorOwners(List<String> body, List<MirrorPart> parts) {
  final Map<int, String> fileOfLine = _fileOfLine(body, parts);
  final slugger = Slugger();
  final owners = <String, String>{};
  var fenced = false;
  for (var i = 0; i < body.length; i++) {
    if (_fence.hasMatch(body[i])) {
      fenced = !fenced;
      continue;
    }
    if (fenced) {
      continue;
    }
    final RegExpMatch? match = _heading.firstMatch(body[i]);
    if (match != null) {
      owners[slugger.slug(plainHeading(match[2]!))] = fileOfLine[i]!;
    }
  }
  return owners;
}

/// Each line of [body] mapped to the output file that holds it.
Map<int, String> _fileOfLine(List<String> body, List<MirrorPart> parts) {
  final result = <int, String>{};
  var cursor = 0;
  for (final MirrorPart part in parts.skip(1)) {
    final int start = _indexOfSection(body, part.lines.first, cursor);
    for (var i = cursor; i < start; i++) {
      result[i] = result[i] ?? mirrorIndex;
    }
    for (var i = start; i < start + part.lines.length; i++) {
      result[i] = part.file;
    }
    cursor = start + part.lines.length;
  }
  for (var i = 0; i < body.length; i++) {
    result[i] = result[i] ?? mirrorIndex;
  }
  return result;
}

/// The index of [heading] in [body] at or after [from].
int _indexOfSection(List<String> body, String heading, int from) {
  for (var i = from; i < body.length; i++) {
    if (body[i] == heading) {
      return i;
    }
  }
  throw StateError('heading not found after line $from: $heading');
}

/// One output file: [lines] with the banner and [nav] prepended, the links
/// rewritten for [self], and the link definitions it uses appended.
String _render(
  List<String> lines,
  Map<String, String> ownerOf,
  String self,
  Map<String, String> definitions, {
  String? nav,
}) {
  final rewritten = <String>[];
  var fenced = false;
  for (final line in lines) {
    if (_fence.hasMatch(line)) {
      fenced = !fenced;
      rewritten.add(line);
    } else {
      rewritten.add(fenced ? line : _rewriteLinks(line, ownerOf, self));
    }
  }

  final String text = rewritten.join('\n').trimRight();
  final List<String> used =
      definitions.keys
          .where((String label) => text.contains('[$label]'))
          .toList()
        ..sort();

  final buffer = StringBuffer()
    ..writeln(mirrorBanner)
    ..writeln();
  if (nav != null) {
    buffer
      ..writeln(nav)
      ..writeln();
  }
  buffer
    ..write(text)
    ..writeln();
  if (used.isNotEmpty) {
    buffer
      ..writeln()
      ..writeln('<!-- manual links; carried from canon by the generator -->')
      ..writeln();
    for (final label in used) {
      buffer.writeln('[$label]: ${definitions[label]}');
    }
  }
  return buffer.toString();
}

/// [line] with every cross-part anchor link given its file, and every
/// relative path moved one directory down.
String _rewriteLinks(String line, Map<String, String> ownerOf, String self) =>
    line
        .replaceAllMapped(_anchorLink, (Match match) {
          final String slug = match[1]!;
          final String? owner = ownerOf[slug];
          if (owner == null || owner == self) {
            return '](#$slug)';
          }
          return '](${owner == mirrorIndex ? mirrorIndex : owner}#$slug)';
        })
        .replaceAll(_upLink, '](../../');
