/// Generates `lib/src/lexer/message_catalog.dart` from the transcribed
/// J 90.04.01 listing. Run from the repository root:
///
///     dart run tool/generate_message_catalog.dart
///
/// The one edit applied to the parsed source is decision D9.6: message
/// 187's stored text ends after `EACH WITH` — the 1962 printout ran
/// straight into message 196's text (a print defect confirmed by scan),
/// and we do not reproduce a defect observed only in a message-file
/// dump. The golden test carries the matching exception.
library;

import 'dart:io';

import 'message_catalog_source.dart';

void main() {
  final String markdown = File(
    'comtran-manuals/J28-6169/90.04-error-messages.md',
  ).readAsStringSync();
  final List<SourceMessage> messages = parseCatalogSource(markdown);
  if (messages.length != 210) {
    throw StateError('expected 210 messages, parsed ${messages.length}');
  }

  final out = StringBuffer('''
/// The complete J 90.04.01 error-message catalog: 210 messages, ids
/// 0,00 through 209,00, texts byte for byte as printed (decision D9.5)
/// including continuation-line indentation.
///
/// GENERATED by `tool/generate_message_catalog.dart` from the
/// transcription `comtran-manuals/J28-6169/90.04-error-messages.md`;
/// do not edit by hand. The golden test
/// (`test/message_catalog_test.dart`) re-parses the transcription and
/// byte-compares every entry. One deliberate divergence: message 187's
/// stored text ends after `EACH WITH` (decision D9.6 — the 1962
/// printout ran on into message 196's text, a print defect).
// ignore_for_file: lines_longer_than_80_chars, reason: message text is byte-exact from the 90.04.01 listing (D9.5) and cannot be wrapped.
library;

import 'messages.dart';

/// Every 90.04 message, keyed by id, in catalog order.
const Map<String, Message> messageCatalog = {
''');
  for (final SourceMessage message in messages) {
    var text = message.text;
    if (message.id == '187,00') {
      final int cut = text.indexOf('EACH WITH');
      text = text.substring(0, cut + 'EACH WITH'.length);
    }
    out.writeln(
      "  '${message.id}': Message('${message.id}', ${_dart(text)}),",
    );
  }
  out.writeln('};');
  final File outputFile = File('lib/src/lexer/message_catalog.dart');
  outputFile.writeAsStringSync(out.toString());

  // DIAG-5: format the generated file so a re-run is a no-op on a clean
  // tree; the committed file must stay dart-format clean.
  final ProcessResult formatted = Process.runSync('dart', [
    'format',
    outputFile.path,
  ]);
  if (formatted.exitCode != 0) {
    throw StateError(
      'dart format failed:\n${formatted.stdout}${formatted.stderr}',
    );
  }
  stdout.writeln('wrote ${messages.length} messages');
}

/// A Dart string literal for [text]; continuation lines become adjacent
/// string literals joined with `\n`. Each line uses single quotes unless
/// the line holds an apostrophe (the 1962 literal delimiter), in which
/// case it uses double quotes, so no delimiter is ever escaped
/// (`prefer_single_quotes`, `avoid_escaping_inner_quotes`).
String _dart(String text) {
  final List<String> lines = text.split('\n');
  String quote(String s) {
    final String delimiter = s.contains("'") ? '"' : "'";
    final String escaped = s
        .replaceAll(r'\', r'\\')
        .replaceAll(r'$', r'\$')
        .replaceAll('\n', r'\n');
    return '$delimiter$escaped$delimiter';
  }

  if (lines.length == 1) {
    return quote(lines.single);
  }
  return [
    for (var i = 0; i < lines.length; i++)
      i == lines.length - 1 ? quote(lines[i]) : '${quote('${lines[i]}\n')}\n',
  ].join('      ');
}
