/// Turns every manual citation in the repository's markdown into a link.
/// Run from the repository root:
///
///     dart run tool/linkify_manual_refs.dart            # rewrite in place
///     dart run tool/linkify_manual_refs.dart --check     # report only
///
/// The tool reads `editors/vscode-punchcard/manual-map.json`, wraps each
/// citation it can resolve in a markdown shortcut reference link, and
/// regenerates one definition block at the end of the file. The inline
/// text gains a pair of brackets and nothing else, so a paragraph never
/// re-wraps. A second run on a swept tree changes nothing.
///
/// Two citation forms are recognized, both defined by CLAUDE.md section 8:
///
/// - `J 02.03.02` — an IBM section code of two to four components. The
///   link goes to the converted file, at the anchor of the heading that
///   holds the code.
/// - `F p. 42` and `F pp. 50–51` — a printed page of F28-8043, alone or
///   as one contiguous range. The whole citation becomes the link text;
///   the link goes to the first page of the range.
///
/// The tool leaves a citation as plain text in six cases. A plain
/// citation is correct; a mangled quotation is not.
///
/// 1. The map has no entry for it. `J 90.06` and `J 02.06.01` are two.
/// 2. It sits in a fenced code block, in an inline code span, on a
///    blockquote line, inside double quotation marks (straight or
///    curly), or inside brackets. The first five hold verbatim 1962
///    text; the sixth holds a link that already exists — which is also
///    what makes the tool idempotent, because its own output is
///    bracketed. A quotation that opened on an earlier line ends at its
///    closing mark; a citation after that mark is plain prose and is
///    linked.
/// 3. It lists pages instead of naming one range (`F pp. 44, 115`). Such
///    a list has no single target. A list of section codes is different:
///    only the first code carries the `J`, so only the first code is a
///    citation, and it is linked.
/// 4. It is not canonical. `J28-6169 02.01`, `Appendix 90.04` and
///    `F28-8043 chapters 2 to 4` all stay as they are.
/// 5. A bracket would turn the line into a link definition — the
///    citation opens the line and a colon follows it.
/// 6. A bracket would turn the line into an inline link, because `(` or
///    `[` follows the citation.
library;

import 'dart:convert';
import 'dart:io';

/// The generated map of citations to manual locations.
const String manualMapPath = 'editors/vscode-punchcard/manual-map.json';

/// The first line of the generated block at the end of a swept file.
const String linkBlockMarker =
    '<!-- manual links; generated by tool/linkify_manual_refs.dart -->';

/// Directories the sweep never enters. `comtran-manuals` is read-only and
/// holds the cited text itself; the rest hold no authored markdown.
const Set<String> skippedDirectories = <String>{
  '.dart_tool',
  '.git',
  'build',
  'coverage',
  'node_modules',
  'comtran-manuals',
};

/// One place a citation points to: the repository-relative `file` of the
/// conversion and the anchor `slug` inside it.
typedef ManualTarget = ({String file, String slug});

/// The part of the manual map this tool needs: `targets` by map key
/// (`J:02.03.02`, `F:42`), and the anchors of each converted file.
typedef ManualMap = ({
  Map<String, ManualTarget> targets,
  Map<String, Set<String>> headingSlugs,
});

final RegExp _fence = RegExp('^ {0,3}(?:```|~~~)');
final RegExp _skippedLine = RegExp(r'^\s*(?:>|<!--)');
final RegExp _definition = RegExp(r'^\[[^\]]+\]: +(\S+)$');
final RegExp _pageList = RegExp(r'^,\s*\d');
final RegExp _digits = RegExp(r'\d+');

/// A citation in its canonical form. Group 1 holds a J section code;
/// groups 2 to 5 hold the F abbreviation, the first page, the dash of a
/// range and the last page. The two lookaheads after the J code stop a
/// longer code or a lettered subsection (`J 02.07.F`) from matching a
/// prefix of itself.
final RegExp citationPattern = RegExp(
  r'\bJ (\d{2}(?:\.\d{2}){1,3})(?!\w)(?!\.\w)'
  '|'
  r'\bF (pp?)\. (\d+)(?:([-–—])(\d+))?(?!\w)',
);

/// Reads the manual map at [path].
ManualMap loadManualMap([String path = manualMapPath]) {
  final decoded =
      jsonDecode(File(path).readAsStringSync()) as Map<String, Object?>;
  final sections = decoded['sections']! as Map<String, Object?>;
  final headings = decoded['headings']! as Map<String, Object?>;
  final targets = <String, ManualTarget>{};
  sections.forEach((String key, Object? value) {
    final entry = value! as Map<String, Object?>;
    targets[key] = (
      file: entry['file']! as String,
      slug: entry['slug']! as String,
    );
  });
  final slugs = <String, Set<String>>{};
  headings.forEach((String file, Object? value) {
    slugs[file] = <String>{
      for (final Object? heading in value! as List<Object?>)
        (heading! as Map<String, Object?>)['slug']! as String,
    };
  });
  return (targets: targets, headingSlugs: slugs);
}

/// Every markdown file the sweep covers, as repository-relative paths in
/// sorted order, below [root].
List<String> markdownFiles([String root = '.']) {
  final paths = <String>[];
  final pending = <String>[''];
  while (pending.isNotEmpty) {
    final String relative = pending.removeLast();
    final directory = relative.isEmpty ? root : '$root/$relative';
    for (final FileSystemEntity entity in Directory(directory).listSync()) {
      final String name = entity.uri.pathSegments
          .where((String segment) => segment.isNotEmpty)
          .last;
      final child = relative.isEmpty ? name : '$relative/$name';
      if (entity is Directory) {
        if (!skippedDirectories.contains(name)) {
          pending.add(child);
        }
      } else if (entity is File && name.endsWith('.md')) {
        paths.add(child);
      }
    }
  }
  return paths..sort();
}

/// The directory part of the repository-relative [path], empty at the
/// repository root.
String directoryOf(String path) {
  final int slash = path.lastIndexOf('/');
  return slash < 0 ? '' : path.substring(0, slash);
}

/// The path of [target] as seen from [fromDirectory]. Both are
/// repository-relative and use forward slashes.
String relativePath(String fromDirectory, String target) {
  final List<String> from = fromDirectory.isEmpty
      ? <String>[]
      : fromDirectory.split('/');
  final List<String> to = target.split('/');
  var common = 0;
  while (common < from.length &&
      common < to.length &&
      from[common] == to[common]) {
    common++;
  }
  return <String>[
    ...List<String>.filled(from.length - common, '..'),
    ...to.skip(common),
  ].join('/');
}

/// Every position of [line] a citation must not touch: an inline code
/// span, a double-quoted run, and a bracketed run. An unclosed span
/// guards the rest of the line, and a quotation mark that closes a
/// quotation from an earlier line guards the line up to itself. Both
/// drop a doubtful citation instead of breaking it.
List<bool> guardedPositions(String line) {
  final guarded = List<bool>.filled(line.length, false);
  void guard(int start, int end) {
    for (var i = start; i < end && i < line.length; i++) {
      guarded[i] = true;
    }
  }

  final List<int> units = line.codeUnits;
  var index = 0;
  while (index < units.length) {
    if (units[index] != 0x60) {
      index++;
      continue;
    }
    final open = index;
    while (index < units.length && units[index] == 0x60) {
      index++;
    }
    final int width = index - open;
    var scan = index;
    var close = -1;
    while (scan < units.length) {
      if (units[scan] != 0x60) {
        scan++;
        continue;
      }
      final start = scan;
      while (scan < units.length && units[scan] == 0x60) {
        scan++;
      }
      if (scan - start == width) {
        close = scan;
        break;
      }
    }
    final int end = close < 0 ? units.length : close;
    guard(open, end);
    index = end;
  }

  for (final (int opener, int closer) in <(int, int)>[
    (0x22, 0x22), // " ... "
    (0x201C, 0x201D), // “ ... ”
    (0x5B, 0x5D), // [ ... ]
  ]) {
    final quotation = opener != 0x5B;
    var open = -1;
    for (var i = 0; i < units.length; i++) {
      final bool closesEarlierLine =
          open < 0 &&
          quotation &&
          units[i] == closer &&
          (opener != closer || _closesEarlierQuotation(units, i));
      if (closesEarlierLine) {
        // The closer of a quotation opened on an earlier line: the text
        // before it is quoted; the rest of the line is plain prose.
        guard(0, i + 1);
      } else if (open < 0 && units[i] == opener) {
        open = i;
      } else if (open >= 0 && units[i] == closer && i != open) {
        guard(open, i + 1);
        open = -1;
      }
    }
    if (open >= 0) {
      guard(open, units.length);
    }
  }
  return guarded;
}

/// Whether the straight quotation mark at [i] reads as the closer of a
/// quotation opened on an earlier line: flush against quoted text on
/// its left, with a space or the line end on its right.
bool _closesEarlierQuotation(List<int> units, int i) =>
    i > 0 &&
    units[i - 1] != 0x20 &&
    (i + 1 == units.length || units[i + 1] == 0x20);

/// The map key of the citation [match]: `J:02.03.02` or `F:42`.
String citationKey(RegExpMatch match) =>
    match[1] != null ? 'J:${match[1]}' : 'F:${match[3]}';

/// Rewrites [markdown], the contents of a file in [directory], against
/// [map]. The returned text carries the bracketed citations and one
/// regenerated definition block.
String linkifyMarkdown({
  required String markdown,
  required String directory,
  required ManualMap map,
}) {
  final List<String> lines = stripLinkBlock(markdown).split('\n');
  final definitions = <String, String>{};
  var inFence = false;
  for (var i = 0; i < lines.length; i++) {
    if (_fence.hasMatch(lines[i])) {
      inFence = !inFence;
      continue;
    }
    if (inFence || _skippedLine.hasMatch(lines[i])) {
      continue;
    }
    lines[i] = _linkifyLine(lines[i], map);
    _collectDefinitions(lines[i], directory, map, definitions);
  }
  final String swept = lines.join('\n');
  if (definitions.isEmpty) {
    return swept;
  }
  final List<String> labels = definitions.keys.toList()
    ..sort(compareCitationLabels);
  final buffer = StringBuffer(swept.trimRight())
    ..write('\n\n')
    ..write(linkBlockMarker)
    ..write('\n\n');
  for (final label in labels) {
    buffer.writeln('[$label]: ${definitions[label]}');
  }
  return buffer.toString();
}

String _linkifyLine(String line, ManualMap map) {
  final List<RegExpMatch> matches = citationPattern.allMatches(line).toList();
  if (matches.isEmpty) {
    return line;
  }
  final List<bool> guarded = guardedPositions(line);
  final buffer = StringBuffer();
  var cursor = 0;
  for (final match in matches) {
    if (guarded.getRange(match.start, match.end).contains(true)) {
      continue;
    }
    final String rest = line.substring(match.end);
    if (rest.startsWith('(') || rest.startsWith('[')) {
      continue;
    }
    if (match[1] == null && _pageList.hasMatch(rest)) {
      continue;
    }
    if (rest.startsWith(':') && line.substring(0, match.start).trim().isEmpty) {
      continue;
    }
    if (!map.targets.containsKey(citationKey(match))) {
      continue;
    }
    buffer
      ..write(line.substring(cursor, match.start))
      ..write('[${match[0]}]');
    cursor = match.end;
  }
  buffer.write(line.substring(cursor));
  return buffer.toString();
}

/// Records one definition for every bracketed citation of [line]. The
/// pass runs after the brackets go on, so it sees the citations this run
/// linked and the ones an earlier run linked alike. That is what keeps
/// the generated block stable across runs.
void _collectDefinitions(
  String line,
  String directory,
  ManualMap map,
  Map<String, String> definitions,
) {
  for (final RegExpMatch match in citationPattern.allMatches(line)) {
    final int after = match.end + 1;
    if (match.start == 0 || line[match.start - 1] != '[') {
      continue;
    }
    if (match.end == line.length || line[match.end] != ']') {
      continue;
    }
    if (after < line.length && (line[after] == '(' || line[after] == '[')) {
      continue;
    }
    final ManualTarget? target = map.targets[citationKey(match)];
    if (target == null) {
      continue;
    }
    definitions[match[0]!] =
        '${relativePath(directory, target.file)}#${target.slug}';
  }
}

/// Removes the generated block from [markdown], with the blank line
/// above it. Text that only looks like the marker is left alone: every
/// line below it must be blank or a link definition.
String stripLinkBlock(String markdown) {
  final List<String> lines = markdown.split('\n');
  final int marker = _markerLine(lines);
  if (marker < 0) {
    return markdown;
  }
  final String head = lines.take(marker).join('\n').trimRight();
  return head.isEmpty ? '' : '$head\n';
}

/// The definitions of the generated block of [markdown], label to
/// target, empty when the file carries no block.
Map<String, String> linkBlockDefinitions(String markdown) {
  final List<String> lines = markdown.split('\n');
  final int marker = _markerLine(lines);
  final definitions = <String, String>{};
  if (marker < 0) {
    return definitions;
  }
  for (final String line in lines.skip(marker + 1)) {
    final RegExpMatch? entry = _definition.firstMatch(line);
    if (entry != null) {
      definitions[line.substring(1, line.indexOf(']'))] = entry[1]!;
    }
  }
  return definitions;
}

int _markerLine(List<String> lines) {
  var marker = -1;
  for (int i = lines.length - 1; i >= 0; i--) {
    if (lines[i].trimRight() == linkBlockMarker) {
      marker = i;
      break;
    }
  }
  if (marker < 0) {
    return -1;
  }
  for (final String line in lines.skip(marker + 1)) {
    if (line.trim().isNotEmpty && !_definition.hasMatch(line)) {
      return -1;
    }
  }
  return marker;
}

/// Orders two citation labels: F before J, then number by number, so
/// that `F p. 2` precedes `F p. 10` and `J 02.05` precedes `J 02.05.05`.
int compareCitationLabels(String a, String b) {
  if (a[0] != b[0]) {
    return a[0].compareTo(b[0]);
  }
  final List<int> left = _numbers(a);
  final List<int> right = _numbers(b);
  for (var i = 0; i < left.length && i < right.length; i++) {
    if (left[i] != right[i]) {
      return left[i].compareTo(right[i]);
    }
  }
  return left.length != right.length
      ? left.length.compareTo(right.length)
      : a.compareTo(b);
}

List<int> _numbers(String label) =>
    _digits.allMatches(label).map((RegExpMatch m) => int.parse(m[0]!)).toList();

void main(List<String> arguments) {
  final bool check = arguments.contains('--check');
  final ManualMap map = loadManualMap();
  var stale = 0;
  var linked = 0;
  for (final String path in markdownFiles()) {
    final file = File(path);
    final String before = file.readAsStringSync();
    final String after = linkifyMarkdown(
      markdown: before,
      directory: directoryOf(path),
      map: map,
    );
    linked += linkBlockDefinitions(after).length;
    if (after == before) {
      continue;
    }
    stale++;
    if (check) {
      stdout.writeln('stale: $path');
    } else {
      file.writeAsStringSync(after);
    }
  }
  stdout.writeln(
    check
        ? '$stale file(s) need a sweep; $linked definitions in all'
        : 'rewrote $stale file(s); $linked definitions in all',
  );
  if (check && stale > 0) {
    exitCode = 1;
  }
}
