/// The one name tally of msg 942 (M4-5; D9.7).
///
/// [J 90.01.05] item a) counts "all program names whether defined by
/// the programmer or generated by the Compiler" in one 3500-name
/// dictionary, so one counter takes the programmer names the resolver
/// enters, the source-order generated names the allocator mints, and
/// every distinct generated symbol the code generator writes. The
/// phases run in that order and each continues the count of the one
/// before it; the 3501st entry draws 942 where it is entered, at the
/// statement that crossed the limit (D9.7's check-on-increment rule).
library;

import '../lexer/diagnostic.dart';
import '../lexer/source_card.dart';
import 'data_messages.dart';

/// The printed capacity of the internal dictionary ([J 90.01.05] a).
const int dictionaryCapacity = 3500;

/// The running count of one job's names.
final class NameTally {
  NameTally(this._diagnostics, {required this.tableLimits, this.count = 0});

  final List<Diagnostic> _diagnostics;

  /// False under the non-historical `--no-table-limits` switch (D9.7).
  final bool tableLimits;

  /// Names entered so far, every phase included.
  int count;

  /// Enters one name, defined or referenced at [anchor] — `null` for a
  /// name no statement owns, which reports at 9999,99 (D11.3).
  void enter(SourceCard? anchor) {
    count += 1;
    if (tableLimits && count == dictionaryCapacity + 1) {
      _diagnostics.add(
        anchor == null
            ? Diagnostic.wholeProgram(msgDictionaryCapacity)
            : Diagnostic(msgDictionaryCapacity, anchor),
      );
    }
  }
}
